name: Eleventy Build
on:
  push:
    branches:
      - development

jobs:
  build_deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: cagov/actions-eleventy@v1.4.1
        with:
          args: --formats=html,njk --input=./pages --output=_site
